name: Android CI

on:
    push:
        branches: [AndroidPublish, beta]
    pull_request:
        branches: [AndroidPublish, beta]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set up JDK 1.8
              uses: actions/setup-java@v2
              with:
                  java-version: "8"
                  distribution: "adopt"

            - name: 체크아웃 Github-Action
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.GIT_TOKEN }} # 토큰값 바꾸기

            - name: 체크아웃 Git Submodule
              run: git submodule update --init --recursive

            - name: Grant execute permission for gradlew
              working-directory: { Directory }
              run: chmod +x gradlew

            - name: Build with Gradle
              working-directory: { Directory }
              run: bash ./gradlew bundleRelease --stacktrace

            - name: Sign TCC App bundle
              id: sign_app
              uses: r0adkll/sign-android-release@v1
              with:
                  releaseDirectory: /app/build/outputs/bundle/release
                  signingKeyBase64: ${{ secrets.SIGNING_KEY }}
                  alias: ${{ secrets.ALIAS }}
                  keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
                  keyPassword: ${{ secrets.KEY_PASSWORD }}

            - name: Upload APK
              uses: actions/upload-artifact@v2
              with:
                  name: app
                  path: /app/build/outputs/bundle/release/app-release.aab
